name: jsonc
description: JSON with comments and trailing commas.
homepage: https://github.com/ubuntu-flutter-community/jsonc.dart
repository: https://github.com/ubuntu-flutter-community/jsonc.dart
issue_tracker: https://github.com/ubuntu-flutter-community/jsonc.dart/issues
version: 0.0.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  source_span: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
